### ISSUE TITLE
Building KNN or pointnet CUDA extensions fails

### ISSUE THREAD

**Issue by Laktus** [Haiyang-W/CAGroup3D#18]
Hi,

When i try to run your code in a colab notebook, the KNN and/or pointnet CUDA extensions fail to install (using your instructions).

```
[1/2] /usr/local/cuda/bin/nvcc  -I/usr/local/lib/python3.10/dist-packages/torch/include -I/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.10/dist-packages/torch/include/TH -I/usr/local/lib/python3.10/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.10 -c -c /content/CAGroup3D/pcdet/ops/knn/src/knn_cuda.cu -o /content/CAGroup3D/pcdet/ops/knn/build/temp.linux-x86_64-cpython-310/src/knn_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=KNN_OP -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++17
[2/2] c++ -MMD -MF /content/CAGroup3D/pcdet/ops/knn/build/temp.linux-x86_64-cpython-310/src/knn.o.d -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/local/lib/python3.10/dist-packages/torch/include -I/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.10/dist-packages/torch/include/TH -I/usr/local/lib/python3.10/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.10 -c -c /content/CAGroup3D/pcdet/ops/knn/src/knn.cpp -o /content/CAGroup3D/pcdet/ops/knn/build/temp.linux-x86_64-cpython-310/src/knn.o -g -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=KNN_OP -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
FAILED: /content/CAGroup3D/pcdet/ops/knn/build/temp.linux-x86_64-cpython-310/src/knn.o 
c++ -MMD -MF /content/CAGroup3D/pcdet/ops/knn/build/temp.linux-x86_64-cpython-310/src/knn.o.d -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/local/lib/python3.10/dist-packages/torch/include -I/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.10/dist-packages/torch/include/TH -I/usr/local/lib/python3.10/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.10 -c -c /content/CAGroup3D/pcdet/ops/knn/src/knn.cpp -o /content/CAGroup3D/pcdet/ops/knn/build/temp.linux-x86_64-cpython-310/src/knn.o -g -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=KNN_OP -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
/content/CAGroup3D/pcdet/ops/knn/src/knn.cpp:6:10: fatal error: THC/THC.h: No such file or directory
    6 | #include <THC/THC.h>
      |          ^~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/CAGroup3D/pcdet/ops/knn/setup.py", line 4, in <module>
    setup(
  File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 1244, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/develop.py", line 115, in install_for_development
    self.run_command('build_ext')
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 1244, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/usr/local/lib/python3.10/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "/usr/local/lib/python3.10/dist-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

I get the following error. Can you maybe help me with this?

**Comment by sucasx** [comment]
Hi bro, I have a similar problem, after executing cd CAGroup3D/
The python setup.py develop command also failed to compile. Did you succeed?

**Comment by Laktus** [comment]
Yes i succeded.
First, after cloning the repository, i installed a conda environment.

```
!pip install condacolab
# Will kill kernel, but we can just execute the next line
import condacolab
condacolab.install()

# creates new environment with the requireements from the modified RfD Net => TODO: Try to create a version that contains CAGroup3D specific environment
!conda create --name CAGroup3DEnv
```

Then i installed python 3.7 and CUDA 11.3 like this,
```
# install spconv
!source activate CAGroup3DEnv && conda install python=3.7
!export CUDA_HOME=/usr/local/cuda-11.3
!source activate CAGroup3DEnv && conda install pytorch==1.10.0 torchvision==0.11.0 torchaudio==0.10.0 cudatoolkit=11.3 -c pytorch -c conda-forge
!source activate CAGroup3DEnv && pip install spconv-cu113
%cd CAGroup3D/
!source activate CAGroup3DEnv && python setup.py develop
```

Compiling the additional CUDA Extensions also worked:

```
%cd ..
# rotate iou ops
%cd CAGroup3D/pcdet/ops/rotated_iou/cuda_op
!source activate CAGroup3DEnv && python setup.py install
# knn ops
%cd ../../knn
!source activate CAGroup3DEnv && python setup.py develop
```

**Comment by sucasx** [comment]
Thank you for your reply, is the device you are using 3090?

**Comment by Laktus** [comment]
No, i just use Google Colab Pro.

**Comment by sucasx** [comment]
OK! I'll try your method first, thanks again!

**Comment by Haiyang-W** [comment]
Great! We have no problem using 3090 here.
