### ISSUE TITLE
After compile the knn, I still got ImportError.

### ISSUE THREAD

**Issue by mrsempress** [Haiyang-W/CAGroup3D#8]
I have done: 
```
# knn ops
cd ../../knn
python setup.py install
```
But I still got ImportError.
`ImportError: cannot import name 'KNN_OP' from 'pcdet.ops.knn' (../pcdet/ops/knn/__init__.py) `

**Comment by Haiyang-W** [comment]
> I have done:
> 
> ```
> # knn ops
> cd ../../knn
> python setup.py install
> ```
> 
> But I still got ImportError. `ImportError: cannot import name 'KNN_OP' from 'pcdet.ops.knn' (../pcdet/ops/knn/__init__.py) `

This problem is a little strange. Looks like you failed to install it. This step should be fine. Maybe you can try it again?

**Comment by mrsempress** [comment]
I've tried reinstalling multiple times, including reconfiguring the environment. After doing the installation of KNN, it has shown the KNN-OP was successful.

**Comment by Haiyang-W** [comment]
> I've tried reinstalling multiple times, including reconfiguring the environment. After doing the installation of KNN, it has shown the KNN-OP was successful.

Nice! Hope everything goes well.

**Comment by mrsempress** [comment]
Sorry, I meant that after it has shown the KNN-OP was successful, it still gets the same import error.

**Comment by mrsempress** [comment]
After I use `python setup.py develop`, the KNN-OP can be imported.
But I got another error:
```
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -11) local_rank: 0 (pid: 83322) of binary: /nvme/huang/anaconda3/envs/CAGroup/bin/python
Traceback (most recent call last):
  File "/nvme/huangi/anaconda3/envs/CAGroup/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nvme/huang/anaconda3/envs/CAGroup/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nvme/huang/anaconda3/envs/CAGroup/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/nvme/huang/anaconda3/envs/CAGroup/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/nvme/huang/anaconda3/envs/CAGroup/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/nvme/huang/anaconda3/envs/CAGroup/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/nvme/huang/anaconda3/envs/CAGroup/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/nvme/huang/anaconda3/envs/CAGroup/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```

**Comment by Haiyang-W** [comment]
We are reproducing this issue. Don't worry about it. I'll get back to you as soon as possible.

**Comment by mrsempress** [comment]
Thank you for your prompt reply; looking forward to your good news.

**Comment by pigtigger** [comment]
Hi @mrsempress
Sorry for the install bug. We reproduced the issue in some cases. You can delete the KNN_OP.egg_info/ dir and build/ dir, then run `python setup.py develop` instead of `python setup.py install`.  We also updated the install guidance in the readme.

**Comment by Haiyang-W** [comment]
Thank you, @pigtigger, for the quick fix. I appreciate your help and hope that everything is going well. 

@mrsempress If you have any questions, please feel free to reach out to us.

Best regards,
Haiyang

**Comment by mrsempress** [comment]
@pigtigger, Sorry, after following your instructions, I still get the same error message.

**Comment by Haiyang-W** [comment]
> @pigtigger, Sorry, after following your instructions, I still get the same error message.

I reproduce this issue in RTX 3090 and successfully reinstall it by the new instructions. Maybe you can try it again from scratch, including the git clone and creating an environment. Note that is "python setup.py develop" not  "python setup.py install".

Best regards
haiyang

**Comment by mrsempress** [comment]
After I reinstall all environment, I can train but not inference.
 ```
epochs: 100%|███████████████████████████████████████████████████████████████████████████████████████�     $ 
Traceback (most recent call last):                                                                                                                                                                                                                                                 
  File "train.py", line 206, in <module>
    main()
  File "train.py", line 199, in main
    dist_test=dist_train
  File "/nvme/huang/CAGroup3D/tools/test.py", line 118, in repeat_eval_ckpt
    model.load_params_from_file(filename=cur_ckpt, logger=logger, to_cpu=dist_test)
  File "../pcdet/models/detectors/detector3d_template.py", line 374, in load_params_from_file
    checkpoint = torch.load(filename, map_location=loc_type)
  File "/nvme/huang/anaconda3/envs/CAGroup/lib/python3.7/site-packages/torch/serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/nvme/huang/anaconda3/envs/CAGroup/lib/python3.7/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
2023-03-16 17:58:45,307   INFO  **********************End training scannet_models/CAGroup3D(default)**********************



2023-03-16 17:58:45,308   INFO  **********************Start evaluation scannet_models/CAGroup3D(default)**********************
2023-03-16 17:58:45,308   INFO  Loading SCANNET dataset
2023-03-16 17:58:45,354   INFO  Total samples for SCANNET dataset: 312

2023-03-16 17:58:45,359   INFO  ==> Loading parameters from checkpoint /nvme/huang/CAGroup3D/output/scannet_models/CAGroup3D/default/ckpt/checkpoint_epoch_10.pth to CPU
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 40212 closing signal SIGTERM
/nvme/huang/anaconda3/envs/CAGroup/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 7 leaked semaphores to clean up at shutdown
  len(cache))
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 40213) of binary: /nvme/huang/anaconda3/envs/CAGroup/bin/python
Traceback (most recent call last):
  File "/nvme/huang/anaconda3/envs/CAGroup/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nvme/huang/anaconda3/envs/CAGroup/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nvme/huang/anaconda3/envs/CAGroup/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/nvme/huang/anaconda3/envs/CAGroup/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/nvme/huang/anaconda3/envs/CAGroup/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/nvme/huang/anaconda3/envs/CAGroup/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/nvme/huang/anaconda3/envs/CAGroup/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/nvme/huang/anaconda3/envs/CAGroup/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

```
And the cpkt is completed, as:
````
-rw-rw-r-- 1 huang huang 1518882099 Mar 16 17:58 /nvme/huang/CAGroup3D/output/scannet_models/CAGroup3D/default/ckpt/checkpoint_epoch_10.pth
```

**Comment by mrsempress** [comment]
The test can be done directly using `test.py`, probably due to the time difference.
